apiVersion: apps/v1
kind: Deployment
metadata:
  name:  starcoin-poly-bridge-frontend-deployment
  namespace: starcoin-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starcoin-poly-bridge-frontend
  template:
    metadata:
      labels:
        app:  starcoin-poly-bridge-frontend
    spec:
      containers:
        - name: react-app
          image: starcoin/starcoin-poly-bridge-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name:  starcoin-poly-bridge-frontend-service
  namespace: starcoin-client
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31200
  selector:
    app:  starcoin-poly-bridge-frontend